### PR TITLE
DOC; Add local setup steps

### LINKED ISSUE #154: Document the project setup steps
**Is your feature or enhancement request related to a problem or limitation? Please describe**

When a new contributor visits the project for contribution. It could be quiet overwhelming to see the whole project structure and different files that are contained in it!
Currently there are step by step docs available on how to setup the project locally.

**Describe your enhancement idea**

- Add the step by step commands required to setup the project
- Add a starter script "template" to confirm if the project was set up correctly
- Document the pitfalls that were faced in the issue #153 for python3.11

**Describe alternatives you've considered**

As this is a growing project, I am hoping the starter docs would change over time. Giving the new contributors something to get started with the setup and start contributing

**Provide any additional context**

I was thinking, I'll first start with the `readme.md` file and then gradually add this to our official docs at `/docs`. But that is open to discussion.

cc- @adam-wolfe @t1m0thyj

### PR DESCRIPTION
**Pull request by bhavukkalra**
**What It Does**
Adds started contribution docs to the project and closes #154 

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**
Since these are DOC changes the tests are not written along with this PR

### CODE REVIEW

**Comment by aadityasinha-dotcom** [comment]
Hey @bhavukkalra, please add Signed-off-by line in the commit messages :relaxed:

**Comment by bhavukkalra** [comment]
Ah I wasn't aware of this check. Thanks for the heads up @aadityasinha-dotcom .Just saw another PR of yours for reference.
Would you suggest that I correct the commit messages in this current PR or create a new one. 
As there has only been one commit so far and I can adjust the code with your suggested change!

**Comment by aadityasinha-dotcom** [comment]
Yes!! you can correct your commit messages with `git rebase HEAD~1 --signoff` then force push your changes to overwrite the branch using `git push --force-with-lease origin next`
Use this [link](https://github.com/zowe/zowe-client-python-sdk/runs/13505619838) as reference :relaxed:

**Comment by bhavukkalra** [comment]
This is actually really interesting to see. I wasn't aware of the signoff's as a concept while comiting but now that I read about it seems like a good practice but nonetheless am usually skeptical to allow rewrite of the commit history any form to a remote branch unless there is a valid reason for it.

But in this case, It was only just one commit. And If this PR ever gets merged in the future the commit history will have one more forced pushed commit. (Not really a bad thing, but If it can be avoided. We should)

**Pull request closed without merging**
