### PR TITLE
Sample scripts

### LINKED ISSUE #336: Update sample scripts in readmes to remove deprecated methods
Sample scripts should be updated to stop using methods that were deprecated in #276.

For example, the recommended zos-files SDK method to upload a USS file has changed from `Files.upload_file_to_uss` to `USSFiles.upload`.

### PR DESCRIPTION
**Pull request by olamidepeterojo**
**What It Does**
Updated sample scripts in readme to stop using deprecated methods

Fixes #336
**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

**Review by zFernand0 — CHANGES_REQUESTED** [review]
Hey @olamidepeterojo,
Please add the missing signoffs

Also, there may be more places that need to be updated (aside from the example mentioned in the issue)

As another example, `files.delete_data_set -> Dataset.delete` 😋

**Comment by olamidepeterojo** [comment]
My apologies for missing out my signoffs again...Will do accordingly

**Review by zFernand0 — CHANGES_REQUESTED** [review]
Hey @olamidepeterojo,
I believe that as part of this issue, we not only want to update test files... but also update the sample scripts provided to users in the various readme files.

Here is a list of what we could review for accuracy:
- [ ] Available commands in: https://github.com/zowe/zowe-client-python-sdk/blob/main/README.md#available-options
- [ ] Scripts in: https://github.com/zowe/zowe-client-python-sdk/tree/main/samples
- [ ] Individual readme files in: `src/*/README.md`
  - For example: https://github.com/zowe/zowe-client-python-sdk/blob/main/src/zos_files/README.md

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @olamidepeterojo!

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
thanks for the contribution

**Pull request merged**
