### PR TITLE
Fix syntax in Auto Responder workflow

### PR DESCRIPTION
**Pull request by t1m0thyj**

### CODE REVIEW

**Comment by adam-wolfe** [comment]
Zowe CLI uses similar syntax. Will we need to change that as well?: 

```
name: Zowe CLI Auto Responder for New Issues
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Process Label Action
        uses: hramos/respond-to-issue-based-on-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by ATorrise** [comment]
> Zowe CLI uses similar syntax. Will we need to change that (and presumably the other CLI repositories) as well?:
> 
> ```
> name: Zowe CLI Auto Responder for New Issues
> # This workflow is triggered when a label is added to an issue.
> on:
>   issues:
>     types: labeled
> 
> jobs:
>   processLabelAction:
>     name: Process Label Action
>     runs-on: ubuntu-latest
>     steps:
>       - uses: actions/checkout@v3
>       - name: Process Label Action
>         uses: hramos/respond-to-issue-based-on-label@v2
>         with:
>           repo-token: ${{ secrets.GITHUB_TOKEN }}
> ```

Hey @adam-wolfe, this auto-commenter has been added to all of the zowe repos we manage during the suite of workflow updates by the team. If it already existed, `uses: actions/checkout@v3` and `uses: hramos/respond-to-issue-based-on-label@v2` were updated.

**Review by ATorrise — APPROVED** [review]
👍

**Review by traeok — APPROVED** [review]

**Comment by t1m0thyj** [comment]
> Zowe CLI uses similar syntax. Will we need to change that (and presumably the other CLI repositories) as well?:

Yes, we'll need to fix it there too, because the `-` needs to come before `uses:` rather than before `name:`

**Comment by t1m0thyj** [comment]
The reason the "build" workflow isn't running is because this PR is targeting the "master" branch, and the "build" workflow is present only in the "next" branch.

**Pull request merged**
