### PR TITLE
Fix logger config

### PR DESCRIPTION
**Pull request by pem70**
**What It Does**
Fixes the bug the logger config would affect other Python application logger [#314].

**How to Test**

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

**Review by traeok — APPROVED** [review]
Changes look good to me, thanks Peizhao!

**Review by zFernand0 — APPROVED** [review]
I like the `Log.close_[file/console]_output()`functions. 🙏🏽 

Is it expected that any `logging.[debug,info,error]("test")` will turn on console_output?(i.e. it's equivalent to running `Log.open_console_output()`)

In contrast, the `closeAll()` function keeps the logger disabled even after a `logging.[xyz]()` call occurs.

<details><summary> Expand this section to vew a small test script</summary>

```python
profile = ProfileManager().load(profile_type="zosmf", validate_schema=False)
ds = Datasets(profile)
console = Console(profile)
jobs = Jobs(profile)

Log.setAllLoggerLevel(logging.DEBUG)
# Log.closeAll() # Keeps console_output off
Log.close_console_output() # Gets enabled after a `logging.` call
# Log.close_file_output()

res = console.issue_command("D T") # You won't see a debug log in the console
print(res['cmd-response'])

logging.error("---- Test ----") # This turns on the consloe_output

res = ds.list('sys1.parmlib*') # You should not see a debug log in the console
for v in res["items"]:
    print(v["dsname"])
```

</details>

**Comment by pem70** [comment]
> This does resolve the problem of logging statements going to the python_sdk.log file 😋
> 
> I like the `Log.close_[file/console]_output()`functions. 🙏🏽
> 
> Is it expected that any `logging.[debug,info,error]("test")` will turn on console_output?(i.e. it's equivalent to running `Log.open_console_output()`)
> 
> In contrast, the `closeAll()` function keeps the logger disabled even after a `logging.[xyz]()` call occurs.
> 
> Expand this section to vew a small test script

It is not an expected behavior, and should be fixed with the update.

**Comment by zFernand0** [comment]
Thank you for addressing the comment 😋

**Pull request merged**
