### PR TITLE
Add matrix to build workflow #199

### PR DESCRIPTION
**Pull request by Aman123lug**
New PR 
Updated PyYAML version `6.0.1`
Changed in sdk.yaml added `pip install -r requirements.txt`

### CODE REVIEW

**Comment by Aman123lug** [comment]
One check is failed because of Failed to build lxml pyproject.toml based 
Any idea how fix this 🙂

**Comment by Aman123lug** [comment]
I think I need to specify the version of lxml

**Comment by t1m0thyj** [comment]
> I think I need to specify the version of lxml

Feel free to update to the latest version in requirements.txt (4.9.3)

**Comment by Aman123lug** [comment]
> > I think I need to specify the version of lxml
> 
> Feel free to update to the latest version in requirements.txt (4.9.3)
> 
> Also, the package `jsoncparser` could be removed from requirements.txt - I don't think we use it anymore

Okay thanks for the Review 😊

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @Aman123lug!

**Comment by Aman123lug** [comment]
> LGTM, thanks @Aman123lug!

Thanks for guiding me. 
As a beginner in open source. I found a great mentor. 🫶

**Review by traeok — APPROVED** [review]
LGTM, thanks @Aman123lug 🙂

**Pull request merged**
